name: OrangeFox - Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: 🦊 Building OrangeFox Recovery for Redmi Note 9T 5G
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: OrangeFox Build
      uses: notsyncing/OrangeFox-Builder@main
      with:
        device_path: 'device/xiaomi/cannon'
        device_tree: 'https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon'
        device_tree_branch: 'lineage-20'
        device_name: 'cannon'
        build_target: 'recoveryimage'
